# Generated by Django 5.2 on 2025-04-13 12:54
from django.db import migrations


def assign_default_author(apps, schema_editor):
    Article = apps.get_model('blog', 'Article')
    User = apps.get_model('auth', 'User')

    default_author = User.objects.get(username='biagio')

    Article.objects.filter(author__isnull=True).update(author=default_author)


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.RunPython(assign_default_author),
    ]
